language: node_js
sudo: false
node_js:
- '7'

branches:
  only:
  - master
  - develop

deploy:
  provider: heroku
  api_key:
    secure: b9ec777b-f764-4ff1-abc5-55ef220ecdef
  app: jira-dvi-gi
  on:
    repo: DVI-GI-2017/Jira__forntend
    branch: master
  skip_cleanup: true

before_script:
  - npm install

script:
  - npm run webpack-prod
