language: node_js
sudo: false
node_js:
- '7'

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: jira-dvi-gi
  on:
    repo: DVI-GI-2017/Jira__frontend
    branch: master
  skip_cleanup: true

before_script:
  - npm install

script:
  - npm run webpack-prod
